// Local-only deterministic answering engine. It never calls a network service.
const knowledge = [
  { topics: ["photosynthesis", "plants", "chlorophyll"], text: "Photosynthesis is how plants, algae, and some bacteria use light energy to turn water and carbon dioxide into sugar. Oxygen is released as a by-product." },
  { topics: ["quantum", "quantum computing", "qubit"], text: "Quantum computing uses qubits, which can represent combinations of 0 and 1. That can make some highly specialized calculations more efficient, but it does not make every program faster." },
  { topics: ["crispr", "gene editing"], text: "CRISPR is a gene-editing system adapted from bacterial defenses. A guide RNA directs a CRISPR-associated protein, often Cas9, to a matching DNA sequence. The protein cuts or alters that sequence, and the cell’s repair process can disable, replace, or correct genetic material. Accuracy, delivery, and unintended edits remain important challenges." },
  { topics: ["antibiotic resistance", "antibiotic"], text: "Antibiotic resistance occurs when bacteria evolve or acquire traits that let them survive an antibiotic. Unnecessary antibiotic use and incomplete treatment increase selection pressure. Infection prevention, appropriate prescribing, diagnostics, vaccination, and new treatments all help limit resistance." },
  { topics: ["vaccine", "vaccination", "immunization"], text: "Vaccines train the immune system to recognize a pathogen or part of it before a dangerous infection occurs. They can reduce severe illness, transmission, or both, depending on the disease and vaccine. Benefits and risks should be assessed using evidence specific to the vaccine and population." },
  { topics: ["relativity", "einstein"], text: "Relativity describes how space, time, gravity, and motion are related. Special relativity explains effects at high relative speed, while general relativity describes gravity as the curvature of spacetime caused by mass and energy." },
  { topics: ["artificial intelligence", "machine learning"], text: "Artificial intelligence is software designed to perform tasks associated with human reasoning, such as recognizing patterns, making predictions, or generating language. Machine learning is one way of building AI from examples." },
  { topics: ["internet", "world wide web"], text: "The internet is the global network that moves data between computers. The World Wide Web is a collection of linked pages and applications that uses the internet." },
  { topics: ["climate change", "global warming", "greenhouse"], text: "Climate change is a long-term shift in climate patterns. Current warming is driven mainly by human emissions of greenhouse gases, especially carbon dioxide from burning fossil fuels." },
  { topics: ["dna", "gene", "genetics"], text: "DNA stores biological instructions. Genes are sections of DNA that help cells make functional molecules, usually proteins." },
  { topics: ["black hole", "black holes"], text: "A black hole is a region where gravity is so strong that, beyond its event horizon, nothing can escape. Many form when very massive stars collapse." },
  { topics: ["solar system", "planets", "planet"], text: "Our solar system includes the Sun, eight planets, dwarf planets, moons, asteroids, and comets. The eight planets are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune." },
  { topics: ["programming", "code", "software"], text: "Programming is writing precise instructions for a computer. Good software design divides a problem into small, testable parts and handles errors deliberately." },
  { topics: ["health", "medical", "medicine"], text: "For health decisions, use qualified medical advice, especially for symptoms, diagnoses, medication, or emergencies. I can provide general education, not a diagnosis." }
];
function calculate(input) { const expression = input.replace(/^(what is|calculate|solve|compute)\s+/i, "").trim().replace(/×/g, "*").replace(/÷/g, "/").replace(/\^/g, "**"); if (!/^[0-9+\-*/().%\s*]+$/.test(expression) || !/[0-9]/.test(expression) || expression.length > 120) return null; try { const result = Function(`"use strict"; return (${expression})`)(); return Number.isFinite(result) ? `The answer is ${result}.` : null; } catch { return null; } }
function answer(question) { const lower = question.toLowerCase().trim(); if (/^(hi|hello|hey|good morning|good evening)[!. ]*$/.test(lower)) return "Hello — I’m Helix, your scientific research assistant. I can explain supported science topics, solve arithmetic, and find studies when live research is available."; if (/who (are|is) (you|helix)|what (are|is) (you|helix)/.test(lower)) return "I’m Helix, a scientific research assistant. I provide local explanations and can search scholarly indexes for evidence when an internet connection is available."; const math = calculate(lower); if (math) return math; const scored = knowledge.map(item => ({ item, score: item.topics.reduce((total, topic) => total + (lower.includes(topic) ? 3 : 0), 0) })).sort((a, b) => b.score - a.score)[0]; if (scored?.score > 0) return scored.item.text; if (/write|draft|email|message/.test(lower)) return "I can help structure a draft. Tell me the audience, purpose, tone, and essential details, and I’ll turn that into a clear message."; return "I don’t have a verified local answer for that exact question. Helix can still search scientific literature when the source connection is available; for high-stakes decisions, check peer-reviewed sources and qualified experts."; }
module.exports = { answer };
